// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bitmagnet-io/bitmagnet/internal/model"
)

func newTorrentFavorite(db *gorm.DB, opts ...gen.DOOption) torrentFavorite {
	_torrentFavorite := torrentFavorite{}

	_torrentFavorite.torrentFavoriteDo.UseDB(db, opts...)
	_torrentFavorite.torrentFavoriteDo.UseModel(&model.TorrentFavorite{})

	tableName := _torrentFavorite.torrentFavoriteDo.TableName()
	_torrentFavorite.ALL = field.NewAsterisk(tableName)
	_torrentFavorite.InfoHash = field.NewField(tableName, "info_hash")
	_torrentFavorite.FavoritesListID = field.NewString(tableName, "favorites_list_id")
	_torrentFavorite.CreatedAt = field.NewTime(tableName, "created_at")

	_torrentFavorite.fillFieldMap()

	return _torrentFavorite
}

type torrentFavorite struct {
	torrentFavoriteDo

	ALL             field.Asterisk
	InfoHash        field.Field
	FavoritesListID field.String
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (t torrentFavorite) Table(newTableName string) *torrentFavorite {
	t.torrentFavoriteDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t torrentFavorite) As(alias string) *torrentFavorite {
	t.torrentFavoriteDo.DO = *(t.torrentFavoriteDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *torrentFavorite) updateTableName(table string) *torrentFavorite {
	t.ALL = field.NewAsterisk(table)
	t.InfoHash = field.NewField(table, "info_hash")
	t.FavoritesListID = field.NewString(table, "favorites_list_id")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *torrentFavorite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *torrentFavorite) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["info_hash"] = t.InfoHash
	t.fieldMap["favorites_list_id"] = t.FavoritesListID
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t torrentFavorite) clone(db *gorm.DB) torrentFavorite {
	t.torrentFavoriteDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t torrentFavorite) replaceDB(db *gorm.DB) torrentFavorite {
	t.torrentFavoriteDo.ReplaceDB(db)
	return t
}

type torrentFavoriteDo struct{ gen.DO }

type ITorrentFavoriteDo interface {
	gen.SubQuery
	Debug() ITorrentFavoriteDo
	WithContext(ctx context.Context) ITorrentFavoriteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITorrentFavoriteDo
	WriteDB() ITorrentFavoriteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITorrentFavoriteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITorrentFavoriteDo
	Not(conds ...gen.Condition) ITorrentFavoriteDo
	Or(conds ...gen.Condition) ITorrentFavoriteDo
	Select(conds ...field.Expr) ITorrentFavoriteDo
	Where(conds ...gen.Condition) ITorrentFavoriteDo
	Order(conds ...field.Expr) ITorrentFavoriteDo
	Distinct(cols ...field.Expr) ITorrentFavoriteDo
	Omit(cols ...field.Expr) ITorrentFavoriteDo
	Join(table schema.Tabler, on ...field.Expr) ITorrentFavoriteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITorrentFavoriteDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITorrentFavoriteDo
	Group(cols ...field.Expr) ITorrentFavoriteDo
	Having(conds ...gen.Condition) ITorrentFavoriteDo
	Limit(limit int) ITorrentFavoriteDo
	Offset(offset int) ITorrentFavoriteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITorrentFavoriteDo
	Unscoped() ITorrentFavoriteDo
	Create(values ...*model.TorrentFavorite) error
	CreateInBatches(values []*model.TorrentFavorite, batchSize int) error
	Save(values ...*model.TorrentFavorite) error
	First() (*model.TorrentFavorite, error)
	Take() (*model.TorrentFavorite, error)
	Last() (*model.TorrentFavorite, error)
	Find() ([]*model.TorrentFavorite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TorrentFavorite, err error)
	FindInBatches(result *[]*model.TorrentFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TorrentFavorite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITorrentFavoriteDo
	Assign(attrs ...field.AssignExpr) ITorrentFavoriteDo
	Joins(fields ...field.RelationField) ITorrentFavoriteDo
	Preload(fields ...field.RelationField) ITorrentFavoriteDo
	FirstOrInit() (*model.TorrentFavorite, error)
	FirstOrCreate() (*model.TorrentFavorite, error)
	FindByPage(offset int, limit int) (result []*model.TorrentFavorite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITorrentFavoriteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t torrentFavoriteDo) Debug() ITorrentFavoriteDo {
	return t.withDO(t.DO.Debug())
}

func (t torrentFavoriteDo) WithContext(ctx context.Context) ITorrentFavoriteDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t torrentFavoriteDo) ReadDB() ITorrentFavoriteDo {
	return t.Clauses(dbresolver.Read)
}

func (t torrentFavoriteDo) WriteDB() ITorrentFavoriteDo {
	return t.Clauses(dbresolver.Write)
}

func (t torrentFavoriteDo) Session(config *gorm.Session) ITorrentFavoriteDo {
	return t.withDO(t.DO.Session(config))
}

func (t torrentFavoriteDo) Clauses(conds ...clause.Expression) ITorrentFavoriteDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t torrentFavoriteDo) Returning(value interface{}, columns ...string) ITorrentFavoriteDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t torrentFavoriteDo) Not(conds ...gen.Condition) ITorrentFavoriteDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t torrentFavoriteDo) Or(conds ...gen.Condition) ITorrentFavoriteDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t torrentFavoriteDo) Select(conds ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t torrentFavoriteDo) Where(conds ...gen.Condition) ITorrentFavoriteDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t torrentFavoriteDo) Order(conds ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t torrentFavoriteDo) Distinct(cols ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t torrentFavoriteDo) Omit(cols ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t torrentFavoriteDo) Join(table schema.Tabler, on ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t torrentFavoriteDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t torrentFavoriteDo) RightJoin(table schema.Tabler, on ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t torrentFavoriteDo) Group(cols ...field.Expr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t torrentFavoriteDo) Having(conds ...gen.Condition) ITorrentFavoriteDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t torrentFavoriteDo) Limit(limit int) ITorrentFavoriteDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t torrentFavoriteDo) Offset(offset int) ITorrentFavoriteDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t torrentFavoriteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITorrentFavoriteDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t torrentFavoriteDo) Unscoped() ITorrentFavoriteDo {
	return t.withDO(t.DO.Unscoped())
}

func (t torrentFavoriteDo) Create(values ...*model.TorrentFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t torrentFavoriteDo) CreateInBatches(values []*model.TorrentFavorite, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t torrentFavoriteDo) Save(values ...*model.TorrentFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t torrentFavoriteDo) First() (*model.TorrentFavorite, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TorrentFavorite), nil
	}
}

func (t torrentFavoriteDo) Take() (*model.TorrentFavorite, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TorrentFavorite), nil
	}
}

func (t torrentFavoriteDo) Last() (*model.TorrentFavorite, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TorrentFavorite), nil
	}
}

func (t torrentFavoriteDo) Find() ([]*model.TorrentFavorite, error) {
	result, err := t.DO.Find()
	return result.([]*model.TorrentFavorite), err
}

func (t torrentFavoriteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TorrentFavorite, err error) {
	buf := make([]*model.TorrentFavorite, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t torrentFavoriteDo) FindInBatches(result *[]*model.TorrentFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t torrentFavoriteDo) Attrs(attrs ...field.AssignExpr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t torrentFavoriteDo) Assign(attrs ...field.AssignExpr) ITorrentFavoriteDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t torrentFavoriteDo) Joins(fields ...field.RelationField) ITorrentFavoriteDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t torrentFavoriteDo) Preload(fields ...field.RelationField) ITorrentFavoriteDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t torrentFavoriteDo) FirstOrInit() (*model.TorrentFavorite, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TorrentFavorite), nil
	}
}

func (t torrentFavoriteDo) FirstOrCreate() (*model.TorrentFavorite, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TorrentFavorite), nil
	}
}

func (t torrentFavoriteDo) FindByPage(offset int, limit int) (result []*model.TorrentFavorite, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t torrentFavoriteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t torrentFavoriteDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t torrentFavoriteDo) Delete(models ...*model.TorrentFavorite) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *torrentFavoriteDo) withDO(do gen.Dao) *torrentFavoriteDo {
	t.DO = *do.(*gen.DO)
	return t
}
