// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"database/sql/driver"
	json "encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	IntegrationTypeQbittorrent IntegrationType = "qbittorrent"
)

var ErrInvalidIntegrationType = fmt.Errorf("not a valid IntegrationType, try [%s]", strings.Join(_IntegrationTypeNames, ", "))

var _IntegrationTypeNames = []string{
	string(IntegrationTypeQbittorrent),
}

// IntegrationTypeNames returns a list of possible string values of IntegrationType.
func IntegrationTypeNames() []string {
	tmp := make([]string, len(_IntegrationTypeNames))
	copy(tmp, _IntegrationTypeNames)
	return tmp
}

// IntegrationTypeValues returns a list of the values for IntegrationType
func IntegrationTypeValues() []IntegrationType {
	return []IntegrationType{
		IntegrationTypeQbittorrent,
	}
}

// String implements the Stringer interface.
func (x IntegrationType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationType) IsValid() bool {
	_, err := ParseIntegrationType(string(x))
	return err == nil
}

var _IntegrationTypeValue = map[string]IntegrationType{
	"qbittorrent": IntegrationTypeQbittorrent,
}

// ParseIntegrationType attempts to convert a string to a IntegrationType.
func ParseIntegrationType(name string) (IntegrationType, error) {
	if x, ok := _IntegrationTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _IntegrationTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return IntegrationType(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationType)
}

// MarshalText implements the text marshaller method.
func (x IntegrationType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *IntegrationType) UnmarshalText(text []byte) error {
	tmp, err := ParseIntegrationType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *IntegrationType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errIntegrationTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *IntegrationType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = IntegrationType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseIntegrationType(v)
	case []byte:
		*x, err = ParseIntegrationType(string(v))
	case IntegrationType:
		*x = v
	case *IntegrationType:
		if v == nil {
			return errIntegrationTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errIntegrationTypeNilPtr
		}
		*x, err = ParseIntegrationType(*v)
	default:
		return errors.New("invalid type for IntegrationType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x IntegrationType) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullIntegrationType struct {
	IntegrationType IntegrationType
	Valid           bool
	Set             bool
}

func NewNullIntegrationType(val interface{}) (x NullIntegrationType) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullIntegrationType) Scan(value interface{}) (err error) {
	if value == nil {
		x.IntegrationType, x.Valid = IntegrationType(""), false
		return
	}

	err = x.IntegrationType.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullIntegrationType) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.IntegrationType.String(), nil
}

// MarshalJSON correctly serializes a NullIntegrationType to JSON.
func (n NullIntegrationType) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.IntegrationType)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullIntegrationType from JSON.
func (n *NullIntegrationType) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}

// MarshalGQL correctly serializes a NullIntegrationType to GraphQL.
func (n NullIntegrationType) MarshalGQL(w io.Writer) {
	bytes, err := json.Marshal(n)
	if err == nil {
		_, _ = w.Write(bytes)
	}
}

// UnmarshalGQL correctly deserializes a NullIntegrationType from GraphQL.
func (n *NullIntegrationType) UnmarshalGQL(v any) error {
	if v == nil {
		return nil
	}
	str, ok := v.(string)
	if !ok {
		return errors.New("value is not a string")
	}
	if str == "null" {
		return nil
	}
	return n.UnmarshalJSON([]byte("\"" + str + "\""))
}
