// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/bitmagnet-io/bitmagnet/internal/protocol"
)

const TableNameTorrentFavorite = "torrent_favorites"

// TorrentFavorite mapped from table <torrent_favorites>
type TorrentFavorite struct {
	InfoHash        protocol.ID `gorm:"column:info_hash;primaryKey;<-:create" json:"infoHash"`
	FavoritesListID string      `gorm:"column:favorites_list_id;not null" json:"favoritesListId"`
	CreatedAt       time.Time   `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
}

// TableName TorrentFavorite's table name
func (*TorrentFavorite) TableName() string {
	return TableNameTorrentFavorite
}
